openssl req \
    -newkey rsa:2048 \
    -x509 \
    -nodes \
    -new \
    -keyout localhost.key \
    -out localhost.crt \
    -subj /CN=Company \
    -config ./openssl.cnf \
    -reqexts SAN \
    -extensions SAN \
    -sha256 \
    -days 3650